name: 'Publish Bikeshed document'
description: 'Publish your Bikeshed source to HTML'
inputs:
  source:
    description: 'The source file'
    required: false
    default: 'dom.bs'
  destination:
    description: 'The destination file'
    required: false
    default: 'index.html'
  parameters:
     description: 'carry other parameters'
     required: false
     default: '--md-Text-Macro="COMMIT-SHA LOCAL COPY'
runs:
  using: 'docker'
  image: 'docker://netwerkdigitaalerfgoed/bikeshed:3.10.0'
  args:
    - bikeshed
    - spec
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
    - ${{ inputs.parameters }}
