name: 'Publish Bikeshed document'
description: 'Publish your Bikeshed source to HTML'
inputs:
  source:
    description: 'The filename of the .bs source'
    required: true
    default: 'index.bs'
  destination:
    description: 'The output filename'
    required: true
    default: 'index.html'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
